### ISSUE TITLE
Mixed Content Warning

### ISSUE THREAD

**Issue by JFickel** [pubnub/pubnub-ember#2]
I tried deploying an app that's similar to your example on Heroku and ran into a mixed content warning immediately. It looks like the PubNub API call in the minified JS isn't HTTPS.

Mixed Content: The page at 'https://glacial-beyond-9671.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ps19.pubnub.com/v2/presence/sub_key/sub-c-0e7a8ffa-7fe/channel/Demo%20Channel?uuid=867&pnsdk=PubNub-JS-Web%2F3.6.7'. This request has been blocked; the content must be served over HTTPS.

**Comment by stephenlb** [comment]
Make sure to enable TLS!  for HTTPS support via 
https://www.pubnub.com/docs/javascript/overview/security.html#_transport_layer_security_with_ssl

``` javascript
 var pubnub = PUBNUB.init({
     publish_key: 'my_pubkey',
     subscribe_key: 'my_subkey',
     ssl: true
  });
```

``` javascript
MyApp.PubNub = PubNubEmber.extend({
  cfg: {
    subscribe_key: 'demo',
    publish_key: 'demo',
    ssl: true,
    uuid: user_id
  }
});
```

**Comment by JFickel** [comment]
Oops, thanks :)

**Comment by stephenlb** [comment]
:+1:
